version: '2'
services:
    ithubbs-app:
        image: ithubbs
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://ithubbs-postgresql:5432/ithubbs
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ithubbs-postgresql:
        extends:
            file: postgresql.yml
            service: ithubbs-postgresql
