version: '2'
services:
    ithubbs-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/ithubbs/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=ithubbs
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
